### ISSUE TITLE
NandToTetris mentor to be nominated

### ISSUE THREAD

**Issue by kgashok** [kgisl/project-ideas#8]
https://github.com/kgisl/project-ideas/blob/master/nandToTetris.md is too important not to pursue. 

I need nominations from the various colleges or IAS or IMS.
Please talk to Dr RR / @vinithmenon and get this defined.

**Comment by 62ramya** [comment]
Discussed with RR sir. Waiting for the nomination from faculties those who are handling COA paper.

**Comment by 62ramya** [comment]
Nominating Subymol Thambi from KGISL-IAS . Still waiting for nominations from faculties

**Comment by kgashok** [comment]
Still no names...

**Comment by 62ramya** [comment]
Sir,

Please find the names:

CSE :  Mr Azath and Mr  Raja
IT : Mr Rajasekaran, Mr Joel Anandraj , Ms Bavani and Ms Dhanalakshimi

**Comment by 62ramya** [comment]
Paid login details will be given tomorrow.

**Comment by kgashok** [comment]
@62ramya Can we get the participants to provide a weekly report? Send an email to this effect.

**Comment by vinithmenon** [comment]
Ramya I did not see any progress on the learning of the students who met me , can you please ask them to update us through weekly report

**Comment by 62ramya** [comment]
@vinithmenon Sure, sir. They are waiting for the links from you to proceed further. I have sent you remainder mail regarding the same sir.

**Comment by 62ramya** [comment]
@kgashok Sure and Noted sir.
